from manim import *

class FTL (Scene):
    def construct(self):
        #Axes creation
        ax = Axes(x_range = (0,9), y_range=(0,9), axis_config={"include_ticks": False}) 
        NE_labels = ax.get_axis_labels(x_label= "E", y_label= "N")
        ts_labels = ax.get_axis_labels(x_label= "s", y_label= "t")
        speedText = MathTex(r"\text{v = } \, 100\,\frac{\text{km}}{\text{h}}")
        spaceTimeText = MathTex(r"\text{Espacio - Tiempo }")
        speedText.shift(2*RIGHT)
        lightSpeedText = MathTex(r"\text{v = }\text{c}")
        lightSpeedText.shift(2*RIGHT)
        iggyText = MathTex(r"\text{""Iggy""}")
        
        #Car, Dog and Vector creation
        car = ImageMobject(filename_or_array= "Auto.png")
        car.shift(2.5*DOWN + 5*LEFT)
        car.scale(0.4)

        dog = ImageMobject(filename_or_array="PerroSinOjo.png")
        dog.scale(0.10)
        dog.shift(2.5*DOWN + 5*LEFT)
        
        v = Vector(LEFT, color = TEAL)
        ar = Arrow(color = PURPLE_E, stroke_width= 5)
        ar.put_start_and_end_on(ax.get_origin(), ax.get_origin() + 5.5*UP)

        #Updater Functions
        coord =[RIGHT, UP, UR]
        i = ValueTracker(0)
        def update_vector(v):
            v.put_start_and_end_on(dog.get_center() + coord[int(i.get_value())], dog.get_center() + 2*coord[int(i.get_value())])
        v.add_updater(update_vector)


        #Start of the animation
        # self.wait(0.5)
        # self.play(FadeIn(car), run_time = 1)
        # self.wait(2.5)
        # self.play(Write(speedText), run_time = 1.5)
        # self.wait(6)
        # self.add(speedText)
        # self.add(car)
        # self.play(Create(ax), Create(NE_labels),run_time= 1.8)
        self.add(ax, NE_labels)
        
        # self.play(Indicate(ax.get_y_axis(), color = RED, scale_factor=1.05))
        # # self.play(Indicate(ax.get_x_axis(), color= BLUE, scale_factor=1.05))
        # car.save_state()
        # self.wait(4)
        # self.wait(1)
        # self.play(car.animate().shift(7*RIGHT), run_time = 3.5)
        
        
        # self.play(Indicate(speedText, color = YELLOW))
        self.wait(1)
       
        # self.play(car.animate().restore(),FadeOut(v), run_time = 2)
        # v.suspend_updating()
        # i.set_value(1)
        # v.resume_updating()
        # v.set_color(RED)
        # self.play(car.animate().shift(0.5*UP))
        # self.play(Rotate(car, PI/2))
        # self.play(car.animate().shift(4*UP), Fade In(v), run_time = 3.5)
        # self.wait(1)
        # self.play(car.animate().restore(), FadeOut(v), run_time = 2)
        # v.set_color(PURPLE)
        # i.set_value(2)
        # self.play(car.animate().shift(0.5*UP))
        # self.play(Rotate(car, PI/4))
        # self.play(FadeIn(v))
        # self.play(car.animate().shift(4*UR),Indicate(ax.get_x_axis(), color= BLUE, scale_factor=1.05), Indicate(ax.get_y_axis(), color = RED, scale_factor=1.05), run_time = 5)
        # self.wait(1)
        # self.play(Write(spaceTimeText))
        # self.play(car.animate().restore(), run_time = 2)
        # self.play(FadeOut(v))
        self.add(car)
        self.wait(1)
        self.play(Write(spaceTimeText), run_time = 1)
        self.wait(1)
        self.play(Unwrite(spaceTimeText),run_time = 1)
        self.wait(1)
        self.play(Indicate(car))
        self.play(Indicate(ax.get_y_axis(), color = RED), Indicate(ax.get_x_axis(), color = TEAL))
        self.wait(1)
        self.play(ReplacementTransform(NE_labels[1], ts_labels[1]))
        self.wait(1)
        self.play(ReplacementTransform(NE_labels[0], ts_labels[0]))
        self.wait(1)
        self.play(Write(lightSpeedText))
        self.wait(1)
        self.play(FadeOut(car))
        # v.remove_updater(update_vector)
        # v.put_start_and_end_on(dog.get_center()+2*RIGHT, dog.get_corner(RIGHT))
        # iggyText.next_to(v, RIGHT)
        
        # self.play(FadeIn(dog))
        # self.wait(0.5)
        # self.play(FadeIn(v), Write(iggyText))
        # self.wait(1)
        # self.play(FadeOut(v), Unwrite(iggyText))
        # self.wait(1)
        # i.set_value(1)
        # v.add_updater(update_vector)
        # v.set_color(RED)
        # self.play(dog.animate().shift(0.5*UP))
        # self.play(Rotate(dog, PI/2))
        # self.play(FadeIn(v))
        # self.play(dog.animate().shift(4*UP), run_time = 3.5)
        # self.wait(1)
        self.remove(dog)
        self.wait(1)
        # self.play(Indicate(dog), color = PURPLE)
        # self.play(Indicate(ax.get_x_axis(), color = RED))
        # self.play(Indicate(ax.get_y_axis(), color = TEAL))
        # self.play(Indicate(lightSpeedText, color = YELLOW))
        # self.remove(dog)
        # self.wait(1)
        self.play(Create(ar), run_time = 1)
        self.wait(1)
        self.play(Rotate(ar, angle = 2*(-PI/36), about_point= ar.get_start()), run_time = 1, rate_functions=linear)
        self.wait(1)
        self.play(Rotate(ar, angle = -PI/2.25, about_point= ar.get_start()), run_time = 10, rate_functions=linear)
        self.wait(1)
        self.play(Indicate(lightSpeedText, color = YELLOW), run_time = 2)
        self.wait(1)
        # self.play(Rotate(ar, angle = -PI/36, about_point= ax.get_origin()), run_time = 2)
        # self.play(Indicate(ax.get_x_axis(), ))
        # self.wait(2)

